function [BW,maskedImage] = segmentImageforSize(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 23-Feb-2020
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(X);

% Polygon drawing
xPos = [39.3900 116.7424 494.2225 587.0455 643.5128 642.7392 3.0343 2.2608];
yPos = [482.0191 139.3477 136.2536 465.7751 485.1132 0.8868 2.4338 481.2456];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Polygon drawing
xPos = [40.9370 585.4984 637.3246 38.6164];
yPos = [472.7368 464.2281 485.1132 482.7927];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Invert mask
BW = imcomplement(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;