function [BW,maskedImage] = segmentImageforSize(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 23-Feb-2020
%----------------------------------------------------


% Threshold image - manual threshold
BW = X > 104;

% Polygon drawing
xPos = [43.7536 116.4809 486.2416 584.2321 636.2895 639.3517 2.4139 4.7105];
yPos = [465.5718 146.3373 135.6196 460.2129 479.3517 6.2416 3.9450 474.7584];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Polygon drawing
xPos = [10.0694 33.8014 582.7010 631.6962];
yPos = [477.0550 470.1651 460.9785 479.3517];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Invert mask
BW = imcomplement(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;